server:
  port:
    8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lambda_order?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: delivery-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update